// Code generated by go-bindata. DO NOT EDIT.
// sources:
// source.html (309B)
// stylesheet.css (588B)

package templates

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _sourceHtml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x4c\xd0\x41\x6b\xfa\x40\x10\x05\xf0\xbb\x9f\xe2\xb9\xe7\x7f\xe2\xff\xde\x4d\xa0\x58\xe9\x45\x68\xd1\xf4\xd0\x63\x4c\x5e\xd8\x25\x9b\x5d\xbb\x3b\xa9\x06\xf1\xbb\x17\x49\xa5\x9e\x1e\x33\xfc\x98\x61\x46\x2f\x5f\xde\xd6\xd5\xe7\xfb\x06\x46\x06\x57\x2e\xf4\x3d\x58\xb7\xe5\x02\x00\xb4\x58\x71\x2c\xb7\x21\xf4\x38\x99\x00\x17\x42\x9f\xd0\x8e\xc3\xe1\x1f\x7c\x38\xe5\x79\xae\x57\x33\x99\xf9\x32\xcb\xb0\x63\xc7\x48\xdf\x10\x62\x08\x9e\x85\xd1\xd7\x0e\xeb\xfd\x1e\x9d\x75\x44\x96\xfd\x62\x67\x7d\x8f\x48\x57\xa8\x24\x93\x63\x32\xa4\x28\xc8\x74\x64\xa1\x84\x67\x59\x35\x29\x29\x98\xc8\xee\x51\xe4\xb7\xee\xc3\xba\xc8\xd6\x46\x36\x62\x83\xff\x1b\x3d\x50\x6a\x18\x91\x63\xc6\xaf\xd1\x7e\x17\x2a\xb2\x8b\x4c\x46\xa1\x09\x5e\xe8\xa5\x50\xff\x9f\xc6\xe8\x8a\xcb\x05\xd5\xf3\xee\x75\x53\xe1\x63\xb7\xc5\xf5\xaa\xca\x85\x5e\xcd\xf7\xeb\x43\x68\xa7\x5b\x79\xcf\xf9\x3b\x3f\x01\x00\x00\xff\xff\xeb\xec\x6f\x03\x35\x01\x00\x00")

func sourceHtmlBytes() ([]byte, error) {
	return bindataRead(
		_sourceHtml,
		"source.html",
	)
}

func sourceHtml() (*asset, error) {
	bytes, err := sourceHtmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "source.html", size: 309, mode: os.FileMode(0644), modTime: time.Unix(1697904119, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x62, 0x53, 0x9d, 0xc4, 0x37, 0xeb, 0x74, 0x4e, 0x3c, 0x5f, 0x76, 0x7e, 0xea, 0x4, 0x6e, 0xa8, 0xe6, 0x5f, 0x0, 0xe4, 0xe5, 0x27, 0xb, 0x68, 0xe8, 0xf3, 0x19, 0x9d, 0x88, 0x8b, 0xee, 0x28}}
	return a, nil
}

var _stylesheetCss = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xb4\x91\xc1\x4e\xc3\x30\x0c\x86\xef\x7d\x0a\x4b\x15\x97\x89\xb2\xb2\x5e\x50\x76\xe2\x51\xdc\xc4\x69\x2d\x32\xa7\x4a\xb2\xd1\x0a\xf1\xee\x68\x4b\x56\x69\x8c\x0b\x87\x1d\x6d\xfd\xdf\xef\xaf\xcd\x76\x03\x31\x2d\x8e\xe2\x8b\x8e\x11\x36\xdb\xaa\xf7\x66\x81\xaf\x0a\x00\xe0\x80\x61\x60\x51\xd0\xee\x2f\xe3\x84\xc6\xb0\x0c\xeb\x6c\xbd\xa4\xc6\xe2\x81\xdd\xa2\xe0\x3d\x30\xba\x67\x88\x28\xb1\x89\x14\xd8\xee\xab\xef\xaa\xaa\x47\x42\x43\xa1\xf4\xf5\xa8\x3f\x86\xe0\x8f\x62\x1a\xed\x9d\x0f\x0a\xea\xae\xeb\x72\xd9\x75\x61\xad\xcd\x8b\x44\x73\x6a\xd0\xf1\x20\x0a\x34\x49\xa2\xf0\xcb\xe2\xb5\x9d\xe6\x7c\x44\x7b\x49\xc8\xb2\xde\x31\x1c\x27\x87\x8b\x02\xeb\x68\xce\xd4\x27\x9b\x34\x9e\x99\xf6\x29\x33\x82\x27\x1e\x30\xb1\x97\x02\x95\xc4\xee\x1c\xf8\xb7\xec\x2a\xb5\xbb\x91\x22\x49\xb7\xed\x6f\xd7\xf6\x7b\x00\x4b\xf2\xef\x1f\x61\x48\xfb\x70\xd1\x55\x20\x5e\x28\x23\x6a\xf4\xa7\xf5\xab\xef\x72\x47\x31\x14\x1c\x97\x70\xdd\xa3\xc8\x63\x9f\xe2\x27\x00\x00\xff\xff\x29\x28\xb4\x05\x4c\x02\x00\x00")

func stylesheetCssBytes() ([]byte, error) {
	return bindataRead(
		_stylesheetCss,
		"stylesheet.css",
	)
}

func stylesheetCss() (*asset, error) {
	bytes, err := stylesheetCssBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "stylesheet.css", size: 588, mode: os.FileMode(0644), modTime: time.Unix(1697903456, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xf2, 0x11, 0xd2, 0xf4, 0xc5, 0xd1, 0x45, 0x6c, 0x3e, 0xa2, 0x2a, 0x9b, 0xb5, 0x5f, 0x63, 0x5a, 0x39, 0xfd, 0xce, 0x64, 0x76, 0x4a, 0x3c, 0x4, 0x4c, 0x3a, 0xb7, 0x4f, 0xe7, 0xc7, 0xdc, 0x1c}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"source.html":    sourceHtml,
	"stylesheet.css": stylesheetCss,
}

// AssetDebug is true if the assets were built with the debug flag enabled.
const AssetDebug = false

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"source.html":    {sourceHtml, map[string]*bintree{}},
	"stylesheet.css": {stylesheetCss, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = os.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
